version: '3.6'
services:
  openconnect:
    image: ubuntu:22.04
    devices: [ /dev/net/tun ]
    cap_add: [ NET_ADMIN ]
    tty: true
    logging:
      driver: "json-file"
      options: { max-size: "1M", max-file: "3" }
    restart: ${RESTART:-no}
    ports: [ "${SOCKS5_PORT:-8022}:8022" ]
    volumes: 
      - ./init.sh:/init.sh:ro
      - ./_danted.conf:/etc/_danted.conf:ro
    command: bash /init.sh
    environment:
      - VPN_USER
      - VPN_PASSWORD
      - VPN_URL
      - VPN_OPTIONS=--disable-ipv6 --protocol=nc --no-dtls --os=linux
