entryPoints:
  http:
    address: :80
  https:
    address: :443
    http:
      tls:
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      email: abc.xyz@gmail.com
      storage: /traefik_acme/acme.json
      httpChallenge:
        entryPoint: http
      tlsChallenge: true

# put tls.certificates settrings into provider/domain.name.yml
# put crt, key files into /etc/traefik/certs/domain.name/...
tls:
  certificates:
    - certFile: /etc/traefik/certs/default/crt
      keyFile: /etc/traefik/certs/default/key

providers:
  docker:
    watch: true
    network: intr
    exposedByDefault: false
    defaultRule: Host(`{{ index .Labels "com.docker.compose.service" }}.{{ index .Labels "com.docker.compose.project" }}.{{ env "BASE_URL" }}`)
  file:
    watch: true
    directory: /etc/traefik/provider
    debugLogGeneratedTemplate: true

global:
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  insecure: true
  dashboard: true
  debug: true
  disableDashboardAd: true
